### ISSUE TITLE
Mongoose adapter - insertOne doesn't exist

### ISSUE THREAD

**Issue by ArthurOnTime** [lucia-auth/examples#27]
At the moment, using mongoose with the mongodb adapter doesn't work.

**insertOne() doesn't exist in mongoose**. 
mongoose uses create() instead.

line 58 : 
replacing `
 await this.Session.insertOne(value); // MUST be replaced for Mongoose
 `
by `
 await this.Session.create(value); // WORKS for Mongoose
 `
 does the trick for mongoose but won't probably work for mongodb adapter.
 
 Maybe using the `save()`collection method which I believe works both in mongoose and mongodb could be the simplest solution to avoid creating a dedicated mongoose adapter ?

**Comment by ArthurOnTime** [comment]
Issue extended and recreated at the right place : https://github.com/lucia-auth/lucia/issues/1440

**Comment by pilcrowOnPaper** [comment]
Closing this in favor of https://github.com/lucia-auth/lucia/issues/1440
