### ISSUE TITLE
Example for google provider with nextjs-app router.

### ISSUE THREAD

**Issue by raunak42** [lucia-auth/examples#28]
There is no example and no documentation on how to use google oauth with lucia.

I recently integrated lucia auth into my application with google provider, specifically Google from "arctic". 
I could help out with the examples and the documentation.

Everything from environment variables, setting up prisma orm to setting up scopes and all will be covered.

**Comment by pilcrowOnPaper** [comment]
I don't see a reason to add a Google example since it's nearly identical GitHub example - just with PKCE.

**Comment by cthed2** [comment]
@pilcrowOnPaper 
Do you mean this documentation https://arctic.js.org/guides/oauth2-pkce?
