### ISSUE TITLE
Sveltekit Stackblitz Demo not working

### ISSUE THREAD

**Issue by Tetramethylmethan** [lucia-auth/examples#36]
White starting the Stackblitz Sveltekit Demo an error occurs.

https://stackblitz.com/github/lucia-auth/examples/tree/main/sveltekit/username-and-password?file=README.md
![image](https://github.com/lucia-auth/examples/assets/34057896/ff86b28e-3758-4b0d-ae20-54f01c66d134)

**Comment by pilcrowonpaper** [comment]
Stackblitz doesn't support `better-sqlite3` unfortunately
