### ISSUE TITLE
Lucia + Passkeys?

### ISSUE THREAD

**Issue by tunnckoCore** [lucia-auth/examples#44]
Would be good to have some basic example. I like the minimalism of Lucia but sometimes it's confusing when everything is separated into small packages.

I don't want to use something like Hanko (they recently released standalone Passkeys API but not quite getting it), or the Exodus' Passkeys Wallet (passkeys.foundation, `@passkeys/core`) which is 2mb just npm package without actual source code.

**Comment by pilcrowonpaper** [comment]
I don't plan to add any more examples using v3. That said, there are a few example repos using passkeys in the org
https://github.com/orgs/lucia-auth/repositories
