### ISSUE TITLE
Why plain SQL statement in sveltekit example?

### ISSUE THREAD

**Issue by bluepuma77** [lucia-auth/examples#46]
I checked the sveltekit example ([link](https://github.com/lucia-auth/examples/tree/main/sveltekit/username-and-password)) and was very surprised to find a plain SQL statement ([link](https://github.com/lucia-auth/examples/blob/main/sveltekit/username-and-password/src/routes/signup/%2Bpage.server.ts#L48)):
```
db.prepare("INSERT INTO user (id, username, password_hash) VALUES(?, ?, ?)").run(
	userId,
	username,
	passwordHash
);
```
Shouldn't the database-adapters ([link](https://github.com/lucia-auth/lucia/tree/main/packages)) handle all the database abstraction?

**Comment by pilcrowonpaper** [comment]
Why not? Lucia doesn't replace every single database calls.

**Comment by bluepuma77** [comment]
@pilcrowOnPaper That does not make sense in my view of separation of concerns. 

Lucia has different database adapters, even some for non-SQL databases. So to be able to interchange the adapters, there shouldn't be any SQL in the examples, but all database interaction should be hidden in the database adapters.
