### ISSUE TITLE
SvelteKit email + password example does not pass the verification check

### ISSUE THREAD

**Issue by uvinw** [lucia-auth/examples#8]
Steps
- Clone repo
- Run dev server
- Create account 
- Try to click verification link printed on console (http://localhost:5174/email-verification)
- Server returns 500 (`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`)

**Comment by itsderinger** [comment]
Cannot reproduce the mentioned behavior, it all worked as intended when I tested it.
